/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * cobacobalogin.java
 *
 * Created on Jun 3, 2021, 8:55:38 PM
 */
package programcuci;

import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Login_form extends javax.swing.JFrame {

    /** Creates new form cobacobalogin */
    public Login_form() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        us = new javax.swing.JTextField();
        atur = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        se = new javax.swing.JButton();
        pa = new javax.swing.JPasswordField();
        sp = new javax.swing.JCheckBox();
        sp1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        sus = new javax.swing.JLabel();
        sps = new javax.swing.JLabel();
        btha = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("LOGIN ADMIN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 11, 174, 45));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Username:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 103, 81, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Password:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 133, 63, 17));

        us.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usActionPerformed(evt);
            }
        });
        jPanel1.add(us, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 100, 160, -1));

        atur.setText("Login");
        atur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aturActionPerformed(evt);
            }
        });
        jPanel1.add(atur, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 100, 32));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 11, -1, 37));

        se.setText("Setting");
        se.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seActionPerformed(evt);
            }
        });
        jPanel1.add(se, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 188, 81, 32));
        jPanel1.add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 131, 160, -1));

        sp.setBackground(new java.awt.Color(102, 102, 255));
        sp.setText("Show Password");
        sp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spActionPerformed(evt);
            }
        });
        sp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                spKeyPressed(evt);
            }
        });
        jPanel1.add(sp, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 158, -1, -1));

        sp1.setBackground(new java.awt.Color(102, 102, 255));
        sp1.setText("Show Password");
        sp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sp1ActionPerformed(evt);
            }
        });
        sp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sp1KeyPressed(evt);
            }
        });
        jPanel1.add(sp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 158, -1, -1));

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        sus.setBackground(new java.awt.Color(102, 102, 255));
        sus.setForeground(new java.awt.Color(102, 102, 255));
        sus.setText("ADMIN");

        sps.setForeground(new java.awt.Color(102, 102, 255));
        sps.setText("12345");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(sus, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(sps)
                .addContainerGap(139, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sus)
                    .addComponent(sps))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 360, 0));

        btha.setText("Hapus");
        btha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthaActionPerformed(evt);
            }
        });
        jPanel1.add(btha, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void aturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aturActionPerformed
        // TODO add your handling code here:  
        try{
            String sql="SELECT * FROM password WHERE username='"+us.getText()+"'AND password='"+pa.getText()+"'";
            java.sql.Connection conn=konfigdatabase.konfigDB();
            java.sql.Statement stm=conn.createStatement();
            java.sql.ResultSet res=stm.executeQuery(sql);
      if(res.next()){
        
        if(us.getText().equals(res.getString("username"))&&pa.getText().equals(res.getString("password")))
           
        {
            JOptionPane.showMessageDialog(null,"Login Berhasil","Info",JOptionPane.INFORMATION_MESSAGE);
            Programcuci coba=new Programcuci();
            coba.setVisible(true);
            this.dispose();
        
        }
        
       
      }else{
            JOptionPane.showMessageDialog(null,"Maaf Password Salah","Error",JOptionPane.ERROR_MESSAGE);
            pa.setText("");
            us.setText("");
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
        
    }//GEN-LAST:event_aturActionPerformed

    private void seActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_seActionPerformed

    private void spActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spActionPerformed
        // TODO add your handling code here:
        if(sp.isSelected())
        {
            pa.setEchoChar((char)0);
        }
        else{
            pa.setEchoChar('*');
        }
            
    }//GEN-LAST:event_spActionPerformed

    private void spKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_spKeyPressed

    private void sp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sp1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp1ActionPerformed

    private void sp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sp1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_sp1KeyPressed

    private void bthaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthaActionPerformed
        // TODO add your handling code here:
        us.setText("");
        pa.setText("");
    }//GEN-LAST:event_bthaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Login_form().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton atur;
    private javax.swing.JButton btha;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPasswordField pa;
    private javax.swing.JButton se;
    private javax.swing.JCheckBox sp;
    private javax.swing.JCheckBox sp1;
    private javax.swing.JLabel sps;
    private javax.swing.JLabel sus;
    private javax.swing.JTextField us;
    // End of variables declaration//GEN-END:variables
}
