/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Cobacoba_aulang.java
 *
 * Created on May 31, 2021, 5:10:36 PM
 */
package programcuci;

import java.awt.HeadlessException;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Programcuci extends javax.swing.JFrame {
    private void clear(){
        nk.setText("");
        na.setText("");
        jk.setSelectedItem("Pilih");
        go.setSelectedItem("Pilih");
        pc.setSelectedItem("Pilih");
        je.setText("");
        ha.setText("");
        di.setText("");
        th.setText("");
        ub.setText("");
        uk.setText("");
    }
     private void tabelhistory(){
        DefaultTableModel model=new DefaultTableModel();
        model.addColumn("SERI");
        model.addColumn("NAMA");
        model.addColumn("KENDARAAN");
        model.addColumn("GOLONGAN");
        model.addColumn("JENIS");
        model.addColumn("HARGA");
        model.addColumn("DISKON");
        model.addColumn("TOTAL");
        model.addColumn("BAYAR");
        model.addColumn("KEMBALI");
        
        
      try{
          String sql="SELECT * FROM history";
          java.sql.Connection conn=konfigdatabase.konfigDB();
          java.sql.Statement stm=conn.createStatement();
          java.sql.ResultSet res=stm.executeQuery(sql);
      while(res.next()){
          model.addRow(new Object[]{
          res.getString(1),res.getString(2),res.getString(3),res.getString(4),res.getString(5),res.getString(6),res.getString(7),res.getString(8),res.getString(9),res.getString(10)});}
       table.setModel(model);           
      }catch(SQLException e){
          
          System.err.println("ERROR"+e.getMessage());
          JOptionPane.showMessageDialog(this,"Pengambilan data dari database gagal","Error",JOptionPane.ERROR_MESSAGE);
      }}
        
        int x=0;
    /** Creates new form Cobacoba_aulang */
    public Programcuci() {
        initComponents();
        tabelhistory();
        clear();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        je = new javax.swing.JTextField();
        ha = new javax.swing.JTextField();
        di = new javax.swing.JTextField();
        th = new javax.swing.JTextField();
        ub = new javax.swing.JTextField();
        uk = new javax.swing.JTextField();
        pc = new javax.swing.JComboBox();
        cd = new javax.swing.JButton();
        ch = new javax.swing.JButton();
        ba = new javax.swing.JButton();
        td = new javax.swing.JButton();
        re = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        lock = new javax.swing.JButton();
        ed = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        clear = new javax.swing.JButton();
        btha = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        na = new javax.swing.JTextField();
        jk = new javax.swing.JComboBox();
        go = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        nk = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Aplikasi Cuci Kendaraan");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 310, 80));

        jLabel2.setText("Golongan:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 130, 30));

        jLabel4.setText("Jenis Kendaraan:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 130, 30));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel3.setText("Paket Cuci:");

        jLabel7.setText("Jenis:");

        jLabel8.setText("Harga:");

        jLabel9.setText("Diskon:");

        jLabel10.setText("Total Harga:");

        jLabel11.setText("Uang Bayar:");

        jLabel12.setText("Uang Kembali:");

        je.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jeActionPerformed(evt);
            }
        });

        th.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thActionPerformed(evt);
            }
        });

        uk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ukActionPerformed(evt);
            }
        });

        pc.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "CB", "CF", "CSF" }));
        pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pcActionPerformed(evt);
            }
        });

        cd.setText("Cek Diskon");
        cd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdActionPerformed(evt);
            }
        });

        ch.setText("Cek Harga");
        ch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chActionPerformed(evt);
            }
        });

        ba.setText("Bayar");
        ba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baActionPerformed(evt);
            }
        });

        td.setText("Tambah Data");
        td.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdActionPerformed(evt);
            }
        });

        re.setText("Reset");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });

        jLabel14.setText("CB=Cuci Biasa");

        jLabel15.setText("CF=Cuci Full");

        jLabel16.setText("CSF=Cuci Snow Full");

        lock.setText("Kunci");
        lock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lockActionPerformed(evt);
            }
        });

        ed.setText("Edit");
        ed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(di, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(th, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ub, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(je, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(48, 48, 48))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(td))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(ed)
                                .addGap(53, 53, 53)
                                .addComponent(lock))
                            .addComponent(uk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(je, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(di, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(th, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ub, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ba)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(td)
                    .addComponent(re, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ed)
                    .addComponent(lock))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 560, 370));

        jPanel2.setBackground(new java.awt.Color(255, 255, 51));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nomor Seri", "Nama", "Kendaraan", "Golongan", "Jenis", "Harga", "Diskon", "Total", "Uang bayar", "Uang Kembali"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("TABEL DATA");

        clear.setText("Clear Table");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        btha.setText("Hapus");
        btha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bthaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(218, 218, 218)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btha)
                        .addGap(56, 56, 56)
                        .addComponent(clear)
                        .addGap(152, 152, 152))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clear)
                    .addComponent(btha))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, 600, 370));

        jLabel6.setText("Nomor Kendaraan:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 130, 30));
        getContentPane().add(na, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 30));

        jk.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Mobil", "Motor" }));
        getContentPane().add(jk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 130, 30));

        go.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pilih", "Member", "None" }));
        go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goActionPerformed(evt);
            }
        });
        getContentPane().add(go, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 130, 30));

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("X");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 20, -1, 40));

        jLabel13.setText("*member discount 5%");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, 230, 30));

        jLabel17.setText("*Kendaraan Roda 4 tambah Rp.10.000");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 230, 30));

        jLabel18.setText("Nama:");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 130, 30));
        getContentPane().add(nk, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 130, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jeActionPerformed

    private void thActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thActionPerformed

    private void ukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ukActionPerformed

    private void pcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pcActionPerformed
        // TODO add your handling code here:
        if(pc.getSelectedItem().toString().equalsIgnoreCase("CB"))
                {
                je.setText("Cuci Biasa");
                ha.setText("10000");
                }
        else if(pc.getSelectedItem().toString().equalsIgnoreCase("CF"))
        {
            je.setText("Cuci Full");
            ha.setText("15000");
        }
        else if(pc.getSelectedItem().toString().equalsIgnoreCase("CSF"))
        {
            je.setText("Cuci Snow Full");
            ha.setText("20000");
        }
        else
        {
         je.setText("");
         ha.setText("");
        }
                
    }//GEN-LAST:event_pcActionPerformed

    private void cdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdActionPerformed
        // TODO add your handling code here:
        String dis;
        double hargars;
        double diskons=0;
        dis=String.valueOf(go.getSelectedItem());
        hargars=Double.parseDouble(ha.getText());
    if (dis.equalsIgnoreCase("Member"))
    {
        diskons=hargars*0.05;
    }         
    else if(dis.equalsIgnoreCase("None"))
    {
        diskons=0;
    }
    else
    {
        di.setText("");
    }
    String desk=Double.toString(diskons);
    di.setText(desk);
    }//GEN-LAST:event_cdActionPerformed

    private void chActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chActionPerformed
        // TODO add your handling code here:
        String a,b;
        double hargar,tots;
        double disk=0;
        double tambahan=0;
        a=String.valueOf(jk.getSelectedItem());
        b=String.valueOf(go.getSelectedItem());
        hargar=Double.parseDouble(ha.getText());
        if(a.equalsIgnoreCase("Mobil"))
        {
            tambahan=10000;
        
        }
        else if(a.equalsIgnoreCase("Motor"))
        {
           tambahan=0;
        }
        if(b.equalsIgnoreCase("Member"))
        {
            disk=hargar*0.05;
        }
        else if(b.equalsIgnoreCase("None"))
        {
            disk=0;              
        }
        
        tots=hargar+tambahan-disk;
        String totstal=Double.toString(tots);
        th.setText(totstal);
        
                
    }//GEN-LAST:event_chActionPerformed

    private void baActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baActionPerformed
        // TODO add your handling code here:
        double kembali,totall,uang;
        String kembalii;
        
        totall=Double.parseDouble(th.getText());
        uang=Double.parseDouble(ub.getText());
        
        
        
        if(uang>=totall){
            kembali=uang-totall;
        kembalii=Double.toString(kembali);
        uk.setText(kembalii);
            
        }
        else if(uang<totall){
        ub.setText("");    
        uk.setText("");
        JOptionPane.showMessageDialog(this,"Uang Anda Kurang","Error",JOptionPane.ERROR_MESSAGE);
        ub.requestFocus();
        }
        
    }//GEN-LAST:event_baActionPerformed

    private void tdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdActionPerformed
        // TODO add your handling code here:
        
        try{
           String sql="INSERT INTO history VALUES('"+nk.getText()+"','"+na.getText()+"','"+jk.getSelectedItem()+"','"+go.getSelectedItem()+"','"+je.getText()+"','"+ha.getText()+"','"+di.getText()+"','"+th.getText()+"','"+ub.getText()+"','"+uk.getText()+"')";
           java.sql.Connection conn=konfigdatabase.konfigDB();
           java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
           pstm.execute();
           JOptionPane.showMessageDialog(this,"Tambah data berhasil","info",JOptionPane.INFORMATION_MESSAGE);
       }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Tambah data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());}
        catch(HeadlessException e){
           JOptionPane.showMessageDialog(this,"Tambah data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }   
        tabelhistory();
        clear();
    }//GEN-LAST:event_tdActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        // TODO add your handling code here:
        nk.setText("");
        na.setText("");
        jk.setSelectedItem("Pilih");
        go.setSelectedItem("Pilih");
        pc.setSelectedItem("Pilih");
        je.setText("");
        ha.setText("");
        di.setText("");
        th.setText("");
        ub.setText("");
        uk.setText("");
        
        
    }//GEN-LAST:event_reActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
         try{String sql="DELETE FROM history";
           java.sql.Connection conn=konfigdatabase.konfigDB();
           java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
           pstm.execute();
           JOptionPane.showMessageDialog(this,"Clear table berhasil","info",JOptionPane.INFORMATION_MESSAGE);
        
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Clear table gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
        catch(HeadlessException e){
           JOptionPane.showMessageDialog(this,"Clear table data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
     tabelhistory();
     clear();
    }//GEN-LAST:event_clearActionPerformed

    private void lockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lockActionPerformed
        // TODO add your handling code here:
        Login_form balik=new Login_form();
        balik.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lockActionPerformed

    private void goActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goActionPerformed

    private void bthaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bthaActionPerformed
        // TODO add your handling code here:
        try{String sql="DELETE FROM history WHERE seri='"+nk.getText()+"'";
           java.sql.Connection conn=konfigdatabase.konfigDB();
           java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
           pstm.execute();
           JOptionPane.showMessageDialog(this,"Hapus data berhasil","info",JOptionPane.INFORMATION_MESSAGE);
        
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Hapus data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
        catch(HeadlessException e){
           JOptionPane.showMessageDialog(this,"Hapus data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
     tabelhistory();
     clear();
        
    }//GEN-LAST:event_bthaActionPerformed

    private void edActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edActionPerformed
        // TODO add your handling code here:
        try{String sql="UPDATE history SET seri='"+nk.getText()+"',nama='"+na.getText()+"',kendaraan='"+jk.getSelectedItem()+"',golongan='"+go.getSelectedItem()+"',jenis='"+je.getText()+"',harga='"+ha.getText()+"',diskon='"+di.getText()+"',total='"+th.getText()+"',uangb='"+ub.getText()+"',uangk='"+uk.getText()+"'WHERE seri='"+nk.getText()+"'";
           java.sql.Connection conn=konfigdatabase.konfigDB();
           java.sql.PreparedStatement pstm=conn.prepareStatement(sql);
           pstm.execute();
           JOptionPane.showMessageDialog(this,"Edit data berhasil","info",JOptionPane.INFORMATION_MESSAGE);
        
        }catch(SQLException e){
           JOptionPane.showMessageDialog(this,"Edit data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
        catch(HeadlessException e){
           JOptionPane.showMessageDialog(this,"Edit data gagal","Error",JOptionPane.ERROR_MESSAGE);
           System.out.print("ERROR"+e.getMessage());  
       }
        tabelhistory();
        clear();
    }//GEN-LAST:event_edActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int baris=table.rowAtPoint(evt.getPoint());
        String noke=table.getValueAt(baris,0).toString();
        nk.setText(noke);
        String namaa=table.getValueAt(baris,1).toString();
        na.setText(namaa);
        String jenk=table.getValueAt(baris,2).toString();
        jk.setSelectedItem(jenk);
        String gol=table.getValueAt(baris,3).toString();
        go.setSelectedItem(gol);
        String jen=table.getValueAt(baris,4).toString();
        je.setText(jen);
        String har=table.getValueAt(baris,5).toString();
        ha.setText(har);
        String dis=table.getValueAt(baris,6).toString();
        di.setText(dis);
        String tots=table.getValueAt(baris,7).toString();
        th.setText(tots);
        String uang=table.getValueAt(baris,8).toString();
        ub.setText(uang);
        String kembali=table.getValueAt(baris,9).toString();
        uk.setText(kembali);
        
        String a=je.getText().toString();
        if(a.equalsIgnoreCase("Cuci Biasa")){
        pc.setSelectedItem("CB");
        }
        else if(a.equalsIgnoreCase("Cuci Full")){
        pc.setSelectedItem("CF");
        }
        else if(a.equalsIgnoreCase("Cuci Snow Full")){
        pc.setSelectedItem("CSF");
        }
    }//GEN-LAST:event_tableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Programcuci().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ba;
    private javax.swing.JButton btha;
    private javax.swing.JButton cd;
    private javax.swing.JButton ch;
    private javax.swing.JButton clear;
    private javax.swing.JTextField di;
    private javax.swing.JButton ed;
    private javax.swing.JComboBox go;
    private javax.swing.JTextField ha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField je;
    private javax.swing.JComboBox jk;
    private javax.swing.JButton lock;
    private javax.swing.JTextField na;
    private javax.swing.JTextField nk;
    private javax.swing.JComboBox pc;
    private javax.swing.JButton re;
    private javax.swing.JTable table;
    private javax.swing.JButton td;
    private javax.swing.JTextField th;
    private javax.swing.JTextField ub;
    private javax.swing.JTextField uk;
    // End of variables declaration//GEN-END:variables
}
